-- Add missing columns to Quote table
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "number" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "tax" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "issueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "validUntil" TIMESTAMP(3);
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "notes" TEXT;

-- Add missing columns to QuoteItem table
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "productName" TEXT;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "total" DOUBLE PRECISION NOT NULL DEFAULT 0;
